version: 2
updates:
  # Enable version updates for app
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"

  # Enable version updates for api
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
