name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test_e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run FastApi
        run: uvicorn main:app &
      - name: Install JS dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Sveltekit
        run: pnpm run build
        env:
          API_URL: http://localhost:8000/
      - name: Start Sveltekit server
        run: pnpm run preview &
      - name: Wait for Sveltekit to start
        run: sleep 10
      - name: Run Playwright tests
        run: npx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:4173/
